export enum ErrorMessage {
  USER_NOT_FOUND = 'User is not found',
  INCORRECT_USER = 'Incorrect user',
  USER_INACTIVE = 'User is inactive',
  EMAIL_EXISTS = 'Email exists',
  ROLE_EXISTS = 'Role exists',
  DATA_EXISTS = 'Data exists',
  IDOL_NOT_FOUND = 'Idol note found',
  DATA_NOT_FOUND = 'Data note found',
  NEWS_NOT_FOUND = 'News note found',
  ACCESS_DENIED = 'Access Denied',
  TOKEN_INVALIDATED = 'Token invalidated',
  PHONE_INVALID = 'Phone invalid',
  ROLE_NOT_FOUND = 'Role not found',
}
